package view;
import javax.swing.*;                      // JFrame, JOptionPane, JFileChooser, dll
import java.awt.event.*;                    // ActionListener, MouseAdapter, dll
import javax.swing.table.DefaultTableModel; // DefaultTableModel
import java.util.ArrayList;                 // ArrayList untuk menyimpan data
import java.io.BufferedReader;              // Membaca file CSV
import java.io.BufferedWriter;              // Menulis file CSV
import java.io.File;                        // File object
import java.io.FileReader;                  // Membaca file CSV
import java.io.FileWriter;                  // Menulis file CSV
import java.io.IOException;                 // Menangani error I/O

import model.Recipe;                        // Class Recipe
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammad Nabil Zaky - 2310010511
 * JFrame utama aplikasi resep makanan
 */
public class RecipeMainFrame extends javax.swing.JFrame {

    // List untuk menyimpan data resep
    private ArrayList<Recipe> recipeList = new ArrayList<>();

    // DefaultTableModel untuk jTable1
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form RecipeMainFrame
     */
    public RecipeMainFrame() {
        initComponents();
        initTable();      // inisialisasi model tabel
    }

    private void initTable() {
        // Kolom: Nama, Bahan, Instruksi, Kategori
        tableModel = new DefaultTableModel(new Object[]{"Nama", "Bahan", "Instruksi", "Kategori"}, 0);
        tblResep.setModel(tableModel);
    }

    private void clearForm() {
        txtResep.setText("");
        txtBahan.setText("");
        txtInstruksi.setText("");
        cbKategori.setSelectedIndex(0);
        tblResep.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNamaResep = new javax.swing.JLabel();
        txtResep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBahan = new javax.swing.JTextArea();
        lblBahan = new javax.swing.JLabel();
        lblInstruksi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstruksi = new javax.swing.JTextArea();
        lblKategori = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResep = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Resep Makanan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Resep Makanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNamaResep.setText("Nama Resep");

        txtBahan.setColumns(20);
        txtBahan.setRows(5);
        jScrollPane1.setViewportView(txtBahan);

        lblBahan.setText("Bahan");

        lblInstruksi.setText("Instruksi");

        txtInstruksi.setColumns(20);
        txtInstruksi.setRows(5);
        jScrollPane2.setViewportView(txtInstruksi);

        lblKategori.setText("Kategori");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan Pembuka", "Makanan Utama", "Makanan Penutup / Dessert", "Cepat Saji", "Minuman", "Camilan / Snack", "Salad / Sayuran" }));

        btnTambah.setBackground(new java.awt.Color(153, 204, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 102, 102));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaResep)
                    .addComponent(lblBahan)
                    .addComponent(lblInstruksi)
                    .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBersih)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtResep, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaResep)
                    .addComponent(txtResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBahan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstruksi)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategori)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersih))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImport.setBackground(new java.awt.Color(153, 204, 255));
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 102, 102));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tblResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Resep", "Bahan", "Instruksi", "Kategori"
            }
        ));
        tblResep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResepMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblResep);

        jScrollPane4.setViewportView(jScrollPane3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImport)
                .addGap(18, 18, 18)
                .addComponent(btnExport)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnExport)
                    .addComponent(btnKeluar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    int selectedRow = tblResep.getSelectedRow();
    if(selectedRow >= 0) {
        // Konfirmasi sebelum mengubah
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin mengubah resep ini?", 
                "Konfirmasi Ubah", 
                JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION) {
            // Ambil data dari form
            String name = txtResep.getText();
            String ingredients = txtBahan.getText();
            String instructions = txtInstruksi.getText();
            String category = (String) cbKategori.getSelectedItem();

            // Update list dan tabel
            Recipe recipe = new Recipe(name, ingredients, instructions, category);
            recipeList.set(selectedRow, recipe);
            tableModel.setValueAt(name, selectedRow, 0);
            tableModel.setValueAt(ingredients, selectedRow, 1);
            tableModel.setValueAt(instructions, selectedRow, 2);
            tableModel.setValueAt(category, selectedRow, 3);

            clearForm();

            // Notifikasi berhasil
            JOptionPane.showMessageDialog(this, "Resep berhasil diubah!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diubah!");
    } // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int selectedRow = tblResep.getSelectedRow();
    if(selectedRow >= 0) {
        // Konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus resep ini?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION) {
            // Hapus dari list dan tabel
            recipeList.remove(selectedRow);
            tableModel.removeRow(selectedRow);
            clearForm();

            // Notifikasi berhasil
            JOptionPane.showMessageDialog(this, "Resep berhasil dihapus!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    // Ambil data dari form
    String name = txtResep.getText();
    String ingredients = txtBahan.getText();
    String instructions = txtInstruksi.getText();
    String category = (String) cbKategori.getSelectedItem();

    // Validasi sederhana
    if(name.isEmpty() || ingredients.isEmpty() || instructions.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    // Konfirmasi sebelum menambah
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menambahkan resep ini?", 
            "Konfirmasi Tambah", 
            JOptionPane.YES_NO_OPTION);
    if(confirm == JOptionPane.YES_OPTION) {
        // Buat objek Recipe baru
        Recipe recipe = new Recipe(name, ingredients, instructions, category);

        // Tambahkan ke list dan tabel
        recipeList.add(recipe);
        tableModel.addRow(new Object[]{name, ingredients, instructions, category});

        // Bersihkan form
        clearForm();

        // Notifikasi berhasil
        JOptionPane.showMessageDialog(this, "Resep berhasil ditambahkan!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    // Konfirmasi sebelum keluar
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar dari aplikasi?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION);
    if(confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi!");
        System.exit(0);
    }// Keluar aplikasi        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tblResepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResepMouseClicked
    // Ambil index baris yang diklik
    int selectedRow = tblResep.getSelectedRow();

    // Pastikan ada baris yang dipilih
    if (selectedRow >= 0) {
        // Ambil data dari list sesuai baris
        Recipe recipe = recipeList.get(selectedRow);

        // Tampilkan data pada form
        txtResep.setText(recipe.getName());
        txtBahan.setText(recipe.getIngredients());
        txtInstruksi.setText(recipe.getInstructions());
        cbKategori.setSelectedItem(recipe.getCategory());
    }     // TODO add your handling code here:
    }//GEN-LAST:event_tblResepMouseClicked

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Pilih File Import");

    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Files", "csv"));
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));

    int userSelection = fileChooser.showOpenDialog(this);
    if(userSelection != JFileChooser.APPROVE_OPTION) return;

    File fileToOpen = fileChooser.getSelectedFile();
    if(fileToOpen == null || !fileToOpen.exists()) {
        JOptionPane.showMessageDialog(this, "File tidak ditemukan!");
        return;
    }

    try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
        recipeList.clear();
        tableModel.setRowCount(0);

        String line;
        boolean firstLine = true;

        if(fileToOpen.getName().toLowerCase().endsWith(".csv")) {
            // CSV
            while((line = reader.readLine()) != null) {
                if(firstLine) { firstLine = false; continue; } // skip header

                // Pisahkan dengan koma, tapi aman untuk koma di dalam quotes
                String[] data = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");
                if(data.length >= 4) {
                    // Gabungkan data lebih dari 4 kolom (jika ada koma di dalam teks)
                    String name = data[0].replaceAll("^\"|\"$", "");
                    String ingredients = data[1].replaceAll("^\"|\"$", "");
                    String instructions = data[2].replaceAll("^\"|\"$", "");
                    String category = data[3].replaceAll("^\"|\"$", "");

                    // Jika ada lebih dari 4 kolom, gabungkan sisanya ke instructions
                    if(data.length > 4) {
                        for(int i = 4; i < data.length; i++) {
                            instructions += "," + data[i].replaceAll("^\"|\"$", "");
                        }
                    }

                    Recipe recipe = new Recipe(name, ingredients, instructions, category);
                    recipeList.add(recipe);
                    tableModel.addRow(new Object[]{name, ingredients, instructions, category});
                }
            }
        } else {
            // TXT
            String name = "", ingredients = "", instructions = "", category = "";
            while((line = reader.readLine()) != null) {
                line = line.trim();
                if(line.startsWith("Nama: ")) name = line.substring(6);
                else if(line.startsWith("Bahan: ")) ingredients = line.substring(7);
                else if(line.startsWith("Instruksi: ")) instructions = line.substring(11);
                else if(line.startsWith("Kategori: ")) category = line.substring(10);
                else if(line.startsWith("----")) {
                    Recipe recipe = new Recipe(name, ingredients, instructions, category);
                    recipeList.add(recipe);
                    tableModel.addRow(new Object[]{name, ingredients, instructions, category});
                    name = ingredients = instructions = category = "";
                }
            }
            if(!name.isEmpty()) {
                Recipe recipe = new Recipe(name, ingredients, instructions, category);
                recipeList.add(recipe);
                tableModel.addRow(new Object[]{name, ingredients, instructions, category});
            }
        }

        JOptionPane.showMessageDialog(this, "Data berhasil diimport dari: " + fileToOpen.getName());
    } catch(IOException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat import: " + e.getMessage());
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
    if(recipeList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tidak ada data untuk diekspor!");
        return;
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan File Export");

    // Filter file TXT dan CSV
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Files", "csv"));
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));

    int userSelection = fileChooser.showSaveDialog(this);

    if(userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        String fileName = fileToSave.getAbsolutePath().toLowerCase();

        // Pastikan ada ekstensi
        if(!fileName.endsWith(".csv") && !fileName.endsWith(".txt")) {
            javax.swing.filechooser.FileFilter filter = fileChooser.getFileFilter();
            if(filter.getDescription().contains("CSV")) fileToSave = new File(fileToSave + ".csv");
            else fileToSave = new File(fileToSave + ".txt");
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            if(fileToSave.getName().toLowerCase().endsWith(".csv")) {
                // Export CSV dengan tanda kutip agar aman jika ada koma
                writer.write("\"Nama Resep\",\"Bahan\",\"Instruksi\",\"Kategori\"");
                writer.newLine();
                for(Recipe r : recipeList) {
                    writer.write("\"" + r.getName() + "\",\"" + r.getIngredients() + "\",\"" + r.getInstructions() + "\",\"" + r.getCategory() + "\"");
                    writer.newLine();
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke CSV!");
            } else {
                // Export TXT
                for(Recipe r : recipeList) {
                    writer.write("Nama: " + r.getName()); writer.newLine();
                    writer.write("Bahan: " + r.getIngredients()); writer.newLine();
                    writer.write("Instruksi: " + r.getInstructions()); writer.newLine();
                    writer.write("Kategori: " + r.getCategory()); writer.newLine();
                    writer.write("---------------------------------------------------"); writer.newLine();
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke TXT!");
            }
        } catch(IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat ekspor: " + e.getMessage());
        }
    }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
         // Konfirmasi sebelum menghapus semua data
    int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus semua data resep?",
            "Konfirmasi Hapus Semua",
            JOptionPane.YES_NO_OPTION);
    if(confirm == JOptionPane.YES_OPTION) {
        recipeList.clear();           // Hapus semua data di list
        tableModel.setRowCount(0);    // Hapus semua baris di tabel
        clearForm();                  // Bersihkan form input
        JOptionPane.showMessageDialog(this, "Semua data resep berhasil dihapus!");
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnBersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBahan;
    private javax.swing.JLabel lblInstruksi;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaResep;
    private javax.swing.JTable tblResep;
    private javax.swing.JTextArea txtBahan;
    private javax.swing.JTextArea txtInstruksi;
    private javax.swing.JTextField txtResep;
    // End of variables declaration//GEN-END:variables
}
